version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: laravel_app
    working_dir: /var/www
    volumes:
      - ./laravel:/var/www
    depends_on:
      - mongodb
    networks:
      - laravel

  nginx:
    image: nginx:alpine
    container_name: nginx_server
    ports:
      - "8080:80"
    volumes:
      - ./laravel:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel

  mongodb:
    image: mongo:latest
    container_name: mongo_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - laravel

  worker:
    build:
      context: .
      dockerfile: docker/python/Dockerfile
    container_name: python_worker
    volumes:
      - ./laravel/public/uploads:/var/www/public/uploads
    depends_on:
      - mongodb
    networks:
      - laravel

networks:
  laravel:

volumes:
  mongo_data: